### PR TITLE
Fix spelling errors in packet builder

### PR DESCRIPTION
**Pull request by zheylmun**
Hello!
Not just a drive-by spell check, wanted to thank you for a great library, offer a bit of help, and ask if you'd be interested in having PTP support added.  I've been working on it a bit separately.  It's not nearly as common as most of the rest of the protocols, and it *is* a payload as opposed to a header, but figured I'd ask.

### CODE REVIEW

**Comment by zheylmun** [comment]
As a note, I goofed and was only seeing one file, so I thought the builder had just gotten missed.  The actual spelling pass over the repo is quite large.  Happy to add the rest of it if you'd like me to tack it on to this PR.

**Comment by JulianSchmid** [comment]
Hi @zheylmun

> As a note, I goofed and was only seeing one file, so I thought the builder had just gotten missed. The actual spelling pass over the repo is quite large. Happy to add the rest of it if you'd like me to tack it on to this PR. [VoidstarSolutions@7fe9265](https://github.com/VoidstarSolutions/etherparse/commit/7fe9265c6df5af65ab710aff357e9e803a8b360e)

Thanks for the PR & flowers. Feel free to add it to this PR if you want to. I will wait with merging until I hear back from you.

> Not just a drive-by spell check, wanted to thank you for a great library, offer a bit of help, and ask if you'd be interested in having PTP support added. I've been working on it a bit separately. It's not nearly as common as most of the rest of the protocols, and it is a payload as opposed to a header, but figured I'd ask.

I avoided including everything bellow the UDP & TCP layer because the waters kind of get muddy where I should stop. Whenever I needed something parsed on these layers I moved the parsing into separate crates (for example https://crates.io/crates/someip_parse & https://crates.io/crates/dlt_parse ). So if you want to do this, I would propose you move PTP parsing into a separate crate or start a new crate that specifically tackles parsing of protocols packaged in UDP or TCP.

Greets
Julian

**Comment by zheylmun** [comment]
Hello @JulianSchmid!
Pushed the rest of the changes.  I've run the checks that I can locally but if you run CI I'll fix anything if I goofed on any of the other platforms.

**Review by JulianSchmid — COMMENTED** [review]
Thanks a lot ❤️.

The corrections I will commit on top myself (you don't need to do anything).

**Pull request merged**
